### ISSUE TITLE
Spider source not updated

### ISSUE THREAD

**Issue by haivp3010** [crawlab-team/crawlab#285]
Sometimes when updating spider, either by uploading new code with the same name, or directly editing spider code on Admin UI, its behavior is not updated when run. The problem is not consistent as sometimes it is updated but sometimes not.

**Update:** Actually it seems that there's a delay before the spider is updated. If I run a spider immediately after changing code, the old spider is run. But after waiting a bit before running again, the new code is executed.

**Comment by tikazyq** [comment]
Hi Hai, I think you’ve already figured out the reason. Yes it’s because of the delay. This is because it takes up to 60 seconds for the spider files be synchronized to the worker nodes before the new one is updated. There might be potential improvement such as adding a notification functionality. I hope this may help regarding your concern.

**Comment by haivp3010** [comment]
> Hi Hai, I think you’ve already figured out the reason. Yes it’s because of the delay. This is because it takes up to 60 seconds for the spider files be synchronized to the worker nodes before the new one is updated. There might be potential improvement such as adding a notification functionality. I hope this may help regarding your concern.

Thanks for the update. That should be fine for now.

**Comment by tikazyq** [comment]
One more thing: right now, the only way for syncing spiders is to upload a zip file. Therefore, editing spider files won’t take effects. We will figure out something more straightforward to users.
