### ISSUE TITLE
Add support for downloading media files and large files.

### ISSUE THREAD

**Issue by Neutrino3316** [crawlab-team/crawlab#568]
Crawlab can't download media files and large files (e.g. jpg files, mp3 files, gif files, zip files and so on.)

A viable approach is to add one type of node. Let's say, MediaWorker. The links of the files (e.g. https://aaa.bbb.com/ccc.mp3) will pass to the MediaWorker node. Then, the media_worker will download the file. MediaWorker node should be able to handle some situation that may occur when downloading large file, such as connection timeout. MediaWorker node may base on some multithreading download library like the [aria2](https://github.com/aria2/aria2).

I believe downloading files (especially image and video files) is a great demand that many appreciate. Though it won't be a easy task to develop such a feature, I'm still looking forward to it.

**Comment by tikazyq** [comment]
Are you talking about the configurable spiders?

**Comment by Neutrino3316** [comment]
> Are you talking about the configurable spiders?

No, I mean can crawlab download files from the links that spiders yielded?
For example, let's crawl this website: https://www.scientificamerican.com/podcast/60-second-science/
We can get the article title and the corresponding mp3 link,. For example, the title is "Espresso May Be Better when Ground Coarser" and the mp3 link is https://flex.acast.com/www.scientificamerican.com/podcast/podcast.mp3?fileId=D4CC60BE-C5F9-4F8E-B503BCEDE92498B9
What I want is that the mp3 link will pass to the MediaWorker node, and then, the MediaWorker will download this mp3.

**Comment by tikazyq** [comment]
Alright, I guess what you are trying to do is a spider workflow that passes crawled data from the a seed spider to another that consumes them. This is something Crawlab doesn't natively support. However, what you can do is to run a spider implemented with a message queue so that two spiders share the same MQ and can pass data via it. If you don't fully understand, you can add my Wechat account "tikazyq1" to discuss further.
